package com.dinidu.lk.pmt.utils;

public enum MessageType {
    OTP, //Done
    SIGN_UP, //Done
    PASSWORD_CHANGE, //Done
    TASK_ASSIGNMENT_NOTIFICATION, //Done
    ISSUE_ASSIGNMENT_NOTIFICATION,  //Done
    UPCOMING_TASK_DEADLINE_REMINDER, //Done
    OVERDUE_TASK_NOTIFICATION, //Done
    TEAM_COLLABORATION_NEW_ASSIGNEE, //Done
    TEAM_COLLABORATION_TEAM_MEMBERS, //Done
    CHECKLIST_MILESTONE_REACHED,
    ISSUE_ATTACHMENTS_NOTIFICATION;
}

